version: "3.9"

services:
  api:
    env_file: .env
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        - DJANGO_SECRET_KEY=${DJANGO_SECRET_KEY}
        - POSTGRES_DB=${POSTGRES_DB}
        - POSTGRES_USER=${POSTGRES_USER}
        - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
        - POSTGRES_PORT=${POSTGRES_PORT}
    container_name: quispai-python
    depends_on:
      - postgres
    ports:
      - "${PYTHON_PORT}:8000"
    tty: true
    command: >
      bash -c "
        ./wait-for-postgres.sh postgres python manage.py migrate &&
        gunicorn config.wsgi:application --bind 0.0.0.0:8000 --workers 3
      "

  postgres:
    container_name: quisapi-postgres
    env_file: .env
    image: postgres:14
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "${POSTGRES_PORT}:5432"
    tty: true
    volumes:
      - quisapi_pg_data:/var/lib/postgresql/data

  pgadmin:
    env_file:
      - .env
    image: dpage/pgadmin4:6
    depends_on:
      - postgres
    environment:
      - PGADMIN_DEFAULT_EMAIL=${EMAIL_ADDRESS}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_PASSWORD}
    tty: true
    ports:
      - '8080:80'

networks:
  app_net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.200.0/24
          gateway: 192.168.200.1

volumes:
  quisapi_pg_data: