version: "3.9"

services:
  postgres:
    env_file: .env
    image: postgres:14
    container_name: quisapi-postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB_NAME}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
      TZ: 'Asia/Tokyo'
    volumes:
      - quisapi_pg_data:/var/lib/postgresql/data
    ports:
      - "${POSTGRES_PORT}:5432"
    tty: true

volumes:
  quisapi_pg_data: