version: "3.9"

services:
  api:
    env_file: .env
    build: .
      args:
        - DJANGO_SECRET_KEY=${DJANGO_SECRET_KEY}
        - POSTGRES_DB=${POSTGRES_DB}
        - POSTGRES_USER=${POSTGRES_USER}
        - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
        - POSTGRES_PORT=${POSTGRES_PORT}
    container_name: quispai-python
    depends_on: postgres
    ports:
      - "${PYTHON_PORT}:8000"
    tty: true

  postgres:
    container_name: quisapi-postgres
    env_file: .env
    image: postgres:14
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "${POSTGRES_PORT}:5432"
    tty: true
    volumes:
      - quisapi_pg_data:/var/lib/postgresql/data

  pgadmin:
    env_file:
      - .env
    image: dpage/pgadmin4:6
    depends_on:
      - postgres
    environment:
      - PGADMIN_DEFAULT_EMAIL=${EMAIL_ADDRESS}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_PASSWORD}
    tty: true
    ports:
      - '8080:80'

volumes:
  quisapi_pg_data:
