version: "3.9"

services:
  api:
    env_file: .env
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        - DJANGO_SECRET_KEY=${DJANGO_SECRET_KEY}
        - POSTGRES_DB=${POSTGRES_DB}
        - POSTGRES_HOST=${POSTGRES_HOST}
        - POSTGRES_USER=${POSTGRES_USER}
        - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
        - POSTGRES_PORT=${POSTGRES_PORT}
    container_name: quisapi-python
    volumes:
      - django_static:/var/www/quisapi/static
#      - gunicorn:/var/run/gunicorn
    depends_on:
      - postgres
    ports:
      - "${PYTHON_PORT}:8000"
    tty: true
    working_dir: /var/www/quisapi
    command: >
      bash -c "
        ./wait-for-it.sh postgres:5432 -- python manage.py migrate &&
        gunicorn config.wsgi:application --bind api:8000 --workers 3
      "

  nginx:
    image: nginx:1.21.6
    container_name: quisapi-nginx
    depends_on:
      - api
    ports:
      - "80:80"
    volumes:
      - ./django.conf:/etc/nginx/conf.d/django.conf
      - django_static:/var/www/quisapi/static
#      - gunicorn:/var/run/gunicorn

  postgres:
    container_name: quisapi-postgres
    env_file: .env
    image: postgres:14
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "${POSTGRES_PORT}:5432"
    tty: true
    volumes:
      - quisapi_pg_data:/var/lib/postgresql/data

volumes:
  quisapi_pg_data:
  django_static:
#  gunicorn:
#    driver: local
